sources:
  - name: ubuntu
    provider: official
    description: "Official Ubuntu Cloud Images"
    homepage: "https://ubuntu.com/"
    strategies:
      - type: "ubuntu-cloud"
        base_url: "https://cloud-images.ubuntu.com/releases"
        versions: ["24.04", "22.04"]

  - name: opensuse
    provider: openSUSE Project
    description: "openSUSE Tumbleweed Cloud Images"
    homepage: "https://get.opensuse.org/tumbleweed/"
    strategies:
      - type: "generic"
        base_url: "https://download.opensuse.org/tumbleweed/appliances"
        versions: ["Latest"]
        template_url: "{base_url}/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2"
        checksum_url: "{base_url}/openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2.sha256"
        checksum_type: "sha256"
        regex: "openSUSE-Tumbleweed-Minimal-VM.x86_64-Cloud.qcow2"

  - name: kali
    provider: Kali Linux
    description: "Kali Linux Cloud Images"
    homepage: "https://www.kali.org/"
    strategies:
      - type: "generic"
        base_url: "https://kali.download/cloud-images/current"
        versions: ["2025.4"]
        template_url: "{base_url}/kali-linux-{version}-cloud-genericcloud-amd64.tar.xz"
        checksum_url: "{base_url}/SHA256SUMS"
        checksum_type: "sha256"
        regex: "kali-linux-{version}-cloud-genericcloud-amd64.tar.xz"
        format: "raw"

  - name: debian
    provider: Debian Project
    description: "Debian GNU/Linux"
    homepage: "https://www.debian.org/"
    strategies:
      - type: "debian-cloud"
        base_url: "https://cloud.debian.org/images/cloud"
        versions: ["12"]

  - name: alpine
    provider: Alpine Linux
    description: "Alpine Linux - Lightweight and secure"
    homepage: "https://alpinelinux.org/"
    strategies:
      - type: "alpine-cdn"
        base_url: "https://dl-cdn.alpinelinux.org/alpine"
        versions: ["3.20", "3.21"]

  - name: cirros
    provider: CirrOS Project
    description: "CirrOS - Test Image"
    homepage: "https://download.cirros-cloud.net"
    ssh_user: cirros
    strategies:
      - type: "generic"
        base_url: "https://download.cirros-cloud.net"
        versions: ["0.6.3"]
        template_url: "{base_url}/{version}/cirros-{version}-x86_64-disk.img"
        checksum_url: "{base_url}/{version}/SHA256SUMS"
        checksum_type: "sha256"
        regex: "cirros-{version}-x86_64-disk.img"

  - name: ubuntu-24.04-lubuntu-minimal
    registry: nido
    provider: "Nido Premium Flavours"
    description: "Lubuntu 24.04 - Lightweight LXQt Desktop with Go and Python pre-installed."
    homepage: "https://github.com/Josepavese/nido"
    strategies:
      - type: "github-release"
        owner: "Josepavese"
        repo: "nido"

  - name: server-hardened
    registry: nido
    provider: "Nido Premium Flavours"
    description: "Hardened Debian with wireguard and firewall pre-configured."
    homepage: "https://github.com/Josepavese/nido"
    strategies:
      - type: "github-release"
        owner: "Josepavese"
        repo: "nido"

