# lib/wizard.sh
# The magical interface for Nido configuration

ask_input() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    local rule="${4:-text}" # text, number, path
    
    local color="${CYAN}"
    local reset="${RESET}"
    local input
    local valid=false

    while [[ "$valid" == "false" ]]; do
        # Fun prompt formatting
        echo -n "  ${color}?${reset} ${BOLD}${prompt}${reset}"
        if [[ -n "$default" ]]; then
            echo -n " ${BLUE}[${default}]${reset}"
        fi
        echo -n ": "
        
        read -r input
        
        # Use default if empty
        if [[ -z "$input" ]]; then
            input="$default"
        fi

        # Validation Logic
        case "$rule" in
            number)
                if [[ "$input" =~ ^[0-9]+$ ]]; then
                    valid=true
                else
                    echo "    ${RED}❌ Error: This magic requires pure numbers (0-9). Try again.${RESET}"
                fi
                ;;
            path)
                # We won't force existence, but we should block empty or suspicious chars if needed
                # For now just ensure it's not empty/garbage
                if [[ -n "$input" ]]; then
                    valid=true
                else
                     echo "    ${RED}❌ Error: The path cannot be void.${RESET}"
                fi
                ;;
            *)  # text
                valid=true
                ;;
        esac
    done
    
    eval "$var_name"='$input'
}

wizard_header() {
    clear
    # Variables expanded because EOF is unquoted
    cat << EOF
  ${BOLD}${CYAN}
         .---.
        /     \\
       | ()_() |    ${PURPLE}NIDO SETUP WIZARD${CYAN}
       |   ^   |    ${BLUE}The Archmagus of VMs${CYAN}
       |  |=|  |
        \_____/
         _|_|_
      ${RESET}
EOF
    echo ""
    echo "  ${INFO} Welcome, Arch-Wizard of Virtualization!"
    echo "  Let's configure your environment for maximum comfiness."
    echo ""
}

run_wizard() {
    wizard_header

    # Load current values to serve as defaults
    local cfg_path="${VMOPS_CONFIG:-$ROOT_DIR/config/config.env}"
    if [[ -f "$cfg_path" ]]; then
        echo "  ${INFO} Reading ancient scrolls from: ${YELLOW}$cfg_path${RESET}"
        set -a
        source "$cfg_path"
        set +a
    else
        echo "  ${WARN} No config found. Starting from scratch (Tabula Rasa)!"
    fi
    echo ""

    # 1. Storage Pool
    ask_input "Where should we store your heavy digital rocks? (Pool Path)" \
        "${POOL_PATH:-/var/lib/libvirt/images}" \
        "WIZ_POOL_PATH" "path"

    # 2. Backup/Templates
    ask_input "Where do you keep your frozen ancestors? (Backup Dir)" \
        "${BACKUP_DIR:-$WIZ_POOL_PATH/backups}" \
        "WIZ_BACKUP_DIR" "path"

    # 3. Network (NAT)
    ask_input "Which network bridge gives life (NAT)?" \
        "${NETWORK_NAT:-default}" \
        "WIZ_NETWORK_NAT" "text"

    # 4. Network (HostOnly)
    ask_input "Which secret tunnel connects you to them? (Host-Only)" \
        "${NETWORK_HOSTONLY:-hostonly56}" \
        "WIZ_NETWORK_HOSTONLY" "text"

    # 5. SSH User
    ask_input "Who holds the keys effectively? (Default SSH User)" \
        "${SSH_USER:-vmuser}" \
        "WIZ_SSH_USER" "text"

    # 6. Resources - RAM
    ask_input "How much brain power (RAM in MB) per default?" \
        "${VM_MEM_MB:-2048}" \
        "WIZ_VM_MEM_MB" "number"
        
    # 7. Resources - CPU
    ask_input "How many hearts (vCPUs) per default?" \
        "${VM_VCPUS:-2}" \
        "WIZ_VM_VCPUS" "number"

    echo ""
    echo "  ${BOLD}${GREEN}Writing the sacred texts...${RESET}"
    
    mkdir -p "$(dirname "$cfg_path")"
    
    cat > "$cfg_path" <<EOF
# Nido Configuration - Generated by Wizard $(date)
# "Keep it secret, keep it safe."

POOL_PATH="$WIZ_POOL_PATH"
BACKUP_DIR="$WIZ_BACKUP_DIR"
VMS_POOL="${VMS_POOL:-vms}"

# Network Construction
NETWORK_NAT="$WIZ_NETWORK_NAT"
NETWORK_HOSTONLY="$WIZ_NETWORK_HOSTONLY"

# Default Species Traits
SSH_USER="$WIZ_SSH_USER"
VM_MEM_MB="$WIZ_VM_MEM_MB"
VM_VCPUS="$WIZ_VM_VCPUS"
VM_OS_VARIANT="${VM_OS_VARIANT:-debian12}"
TEMPLATE_DEFAULT="${TEMPLATE_DEFAULT:-template-headless}"
GRAPHICS="${GRAPHICS:-spice}"
VM_NESTED="${VM_NESTED:-false}"
WAIT_TIMEOUT="${WAIT_TIMEOUT:-60}"
EOF

    echo "  ${OK} Configuration saved to: ${YELLOW}$cfg_path${RESET}"
    echo ""
    
    # Validation / Humor Check
    if [[ ! -d "$WIZ_POOL_PATH" ]]; then
        echo "  ${WARN} Note: The pool path '${WIZ_POOL_PATH}' doesn't exist yet."
        echo "        The spirits might complain later if you don't create it."
    fi
    
    echo "  ${BIRD} Setup complete! May your uptimes be high and pings be low."
    echo ""
}
